Added start,end,getcurrentmeeting methods, added additional fields to…
eTutorTeam/eTutor.BackEnd pull request #15
Opened 2020-01-02 00:13 UTC by AngelR24

… meeting, added payment amount (Const)

2020-01-02 02:02 UTC, juandozuna requested changes
Cosas pendientes que se deben de hacer en general
- Se debe de hacer integración con la rama de `develop`
- Antes de un PR, deben de asegurarse de que lo que están mandando funcionan, ya que vi algunas cosas que hasta que no se prueben junto con la aplicación, no puedo decir si hay cambiarlas u otra cosa. Por ende antes de integrar con develop, hay que hacer pruebas de estos endpoints trabajando junto con el flujo ya de creación de la tutoría

2020-01-02 02:02 UTC, juandozuna commented on eTutor.SOLUTION/eTutor.Core/Managers/MeetingsManager.cs
> +            var meeting = await _meetingRepository.Find(s => s.Id == meetingId);
Debes de validar que el `meeting` está con estado accepted antes de proceder a iniciar la misma

2020-01-02 02:02 UTC, juandozuna commented on eTutor.SOLUTION/eTutor.Core/Managers/MeetingsManager.cs
> +            var meeting = await _meetingRepository.Find(s => s.Id == meetingId);
Debes de validar que el `meeting` tiene el status `InProgress` antes de proceder a decir que termino

2020-01-02 02:02 UTC, juandozuna commented on eTutor.SOLUTION/eTutor.Core/Managers/MeetingsManager.cs
> +            decimal hours =meeting.EndDateTime.Hour - meeting.RealStartedDateTime.Hour;
Pudises refactorizar el `if else` de abajo, para que esté en una sola línea de código de la siguiente forma
```c#
result = hours < 1 ? amountPerHour : amountPerHour * hours
```

2020-01-02 02:02 UTC, juandozuna commented on eTutor.SOLUTION/eTutor.Core/Managers/NotificationManager.cs
> +            if (userId == student.Id)
No es necesario hacer un `else if` puedes agregar la condición booleana dentro del primer `if` de la siguiente forma
```c#
if (userId == student.Id || parents.Any(p => p.Id == userId) {
    calculateAmount = true;
}
```

2020-01-02 02:02 UTC, juandozuna commented on eTutor.SOLUTION/eTutor.ServerApi/Controllers/MeetingController.cs
> +        [HttpPut("start-meeting/{meetingId}")]
Este debería de ser un `HttpPatch` ya que el `HttpPut` se utiliza cuando el objeto completo va a ser reemplazado

2020-01-02 02:02 UTC, juandozuna commented on eTutor.SOLUTION/eTutor.ServerApi/Controllers/MeetingController.cs
> +        [HttpPut("end-meeting/{meetingId}")]
Deberia de ser un `HttpPatch`

2020-01-02 02:02 UTC, juandozuna commented on eTutor.SOLUTION/eTutor.Core/Models/Meeting.cs
> +        public int? CancelerUserId { get; set; }
No especificaste la relación con Entity Framework, por lo que el mismo no genero los foregin keys. Debes de terminar de hacer la relación para que EF haga las relaciones de FK e internamente se valide que el valor en ese campo sea de un usuario real, dado el caso que se fuese a tocar la BD

2020-01-04 17:15 UTC, AngelR24 commented on eTutor.SOLUTION/eTutor.Core/Managers/NotificationManager.cs
> +            if (userId == student.Id)
Es cierto

2020-01-04 17:17 UTC, AngelR24 commented on eTutor.SOLUTION/eTutor.Core/Models/Meeting.cs
> +        public int? CancelerUserId { get; set; }
Algo como esto me imagino 
`public User CancelerUser { get; set; }`

2020-01-05 00:41 UTC, juandozuna commented on eTutor.SOLUTION/eTutor.Core/Models/Meeting.cs
> +        public int? CancelerUserId { get; set; }
Correcto

2020-01-05 00:43 UTC, juandozuna approved these changes

2020-01-05 03:38 UTC, merged